# Generated by Django 4.1.13 on 2024-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=55)),
                ('userLastName', models.CharField(max_length=55)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userNumber', models.IntegerField()),
                ('usergander', models.CharField(max_length=50)),
                ('userDOB', models.CharField(max_length=11)),
                ('userName', models.CharField(max_length=55)),
                ('userPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
